[package]
name = "blog-renderer-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
serde_json = "1.0"
handlebars = "4.3.5"
serde = { version = "1.0", features = ["derive"] }
